# 4.1 Numpy

    メモ
    ・多次元配列のデータをリストより扱いやすい
    ・配列用のndarrayと行列用のmatrixがある
    ・専用のメソッドが用意されている

In [1]:
#importから
import numpy as np

1次元配列

In [2]:
#array関数にリストを渡すことでndarrayオブジェクトが作られる
#中に1次元配列を格納している
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
#typeで型を確認してみる
type(a)

numpy.ndarray

In [6]:
#1次元配列で3要素
a.shape

(3,)

2次元配列

In [7]:
b = np.array([[1,2,3],[4,5,6]])

In [8]:
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
#2×3行列
b.shape

(2, 3)

変形(reshape)
・次元の変換

In [10]:
#次元の変換
c1 = np.array([1,2,3,4,5,6])
print(c1)

[1 2 3 4 5 6]


In [11]:
#2×3行列に変換する
c2 = c1.reshape((2,3))
print(c2)

[[1 2 3]
 [4 5 6]]


In [12]:
#ravelメソッド
#1次元配列に戻す
c3 = c2.ravel()

print(c3)

[1 2 3 4 5 6]


In [13]:
#flattenメソッド
#copyを返す

c4 = c2.flatten()
print(c4)

[1 2 3 4 5 6]


In [14]:
#メモ
#ravel()は参照を返す
#flattenはコピーを返す

データ型(dtype)

In [15]:
#numpy配列の要素のデータ型を確認する

In [16]:
print("aの型: ",a.dtype)
print("bの型: ",b.dtype)
print("c1の型: ",c1.dtype)

aの型:  int32
bの型:  int32
c1の型:  int32


In [17]:
#int16で宣言する場合
d = np.array([1,2],dtype = np.int16)
print("dの型: ",d.dtype)

dの型:  int16


In [18]:
#型の変換
#astype()を使用する
print(d.astype(np.float16).dtype)

float16


深いコピー(copy)

In [20]:
a1 = a
print(a1)

[1 2 3]


In [22]:
a1[1] = 5

#どっちも変わる
print("a",a)
print("a1",a1)

a [1 5 3]
a1 [1 5 3]


In [25]:
a2 = a.copy()
a2[0] = 6

#a2のみ変更される
print("a",a)
print("a2",a2)

#=では参照先が同じ　　　　　　　浅いコピー
#.copyはコピーで参照先は異なる　深いコピー

a [1 5 3]
a2 [6 5 3]


数列を返す(arange)

In [27]:
#0～9までの整数が要素の配列
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
print(np.arange(1,11))#1～10まで
print(np.arange(1,10,2))#2ことばしで生成

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [31]:
f = np.random.random((2,3))
print(f)#タプルで指定した2行3列のランダムで生成した配列(0～1)

[[0.53953059 0.64860363 0.24444944]
 [0.73290416 0.42361745 0.26591958]]


In [33]:
#シード 乱数を固定するのがシード値
np.random.seed(123)
np.random.random((3,2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [36]:
#rand関数
#random関数はタプルだが、rand関数は2つの引数
np.random.seed(123)
np.random.rand(3,2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [37]:
#randint関数は整数値を生成
np.random.seed(123)
np.random.randint(1,10)

3

In [42]:
np.random.seed(123)
#タプルを追加するとn行m列
np.random.randint(1,10,(3,3))

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [46]:
#uniform関数はランダムな小数値
np.random.seed(123)
np.random.uniform(0.0,5.0,size=(2,3))#タプルでもいける

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [50]:
#標準正規分布からの乱数出力
#平均0　分散1
np.random.seed(123)
np.random.randn(4,2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

同じ要素の配列

In [54]:
#全部0と全部1の配列
#全部0
print(np.zeros((2,3)))

#全部1
print(np.ones((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


単位行列

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
#full関数 同じ要素を持つ配列を生成
np.full(3,3.14) #full(個数,値)

array([3.14, 3.14, 3.14])

    np.nanについて
    not a numberで数値ではないことを表す(データ型はfloat)

範囲指定

In [59]:
#linspace関数
#等間隔に区切った要素を返す
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [60]:
#diff関数
#前後の要素との差分を出力
l = np.array([2,2,6,1,3])
np.diff(l)

array([ 0,  4, -5,  2])

In [66]:
#concatenate関数
#連結させる
print(a)
print(a1)

#axis = 1で列方向に連結できる
np.concatenate([a,a1])

[1 5 3]
[1 5 3]


array([1, 5, 3, 1, 5, 3])

In [67]:
#hstack関数
#concatenate関数のaxis=1と同じ効果
b1 = [[10],[20]]

np.hstack([b,b1])

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [68]:
#vstack関数
#行方向に連結する
b2 = np.array([2,2,3])

np.vstack([b,b2])

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 3]])

分割

In [69]:
#hsplit関数　列方向
#vsplit関数　行方向

転置

In [71]:
#配列.T　行列を入れ替える

print(b)
print(b.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
