# 4.1 Numpy

    メモ
    ・多次元配列のデータをリストより扱いやすい
    ・配列用のndarrayと行列用のmatrixがある
    ・専用のメソッドが用意されている

In [1]:
#importから
import numpy as np

1次元配列

In [15]:
#array関数にリストを渡すことでndarrayオブジェクトが作られる
#中に1次元配列を格納している
a = np.array([1,2,3])

In [9]:
a

array([1, 2, 3])

In [10]:
print(a)

[1 2 3]


In [11]:
#typeで型を確認してみる
type(a)

numpy.ndarray

In [13]:
#1次元配列で3要素
a.shape

(3,)

2次元配列

In [16]:
b = np.array([[1,2,3],[4,5,6]])

In [17]:
print(b)

[[1 2 3]
 [4 5 6]]


In [19]:
#2×3行列
b.shape

(2, 3)

変形(reshape)
・次元の変換

In [21]:
#次元の変換
c1 = np.array([1,2,3,4,5,6])
print(c1)

[1 2 3 4 5 6]


In [24]:
#2×3行列に変換する
c2 = c1.reshape((2,3))
print(c2)

[[1 2 3]
 [4 5 6]]


In [27]:
#ravelメソッド
#1次元配列に戻す
c3 = c2.ravel()

print(c3)

[1 2 3 4 5 6]


In [29]:
#flattenメソッド
#copyを返す

c4 = c2.flatten()
print(c4)

[1 2 3 4 5 6]


In [30]:
#メモ
#ravel()は参照を返す
#flattenはコピーを返す

データ型(dtype)

In [31]:
#numpy配列の要素のデータ型を確認する

In [35]:
print("aの型: ",a.dtype)
print("bの型: ",b.dtype)
print("c1の型: ",c1.dtype)

aの型:  int32
bの型:  int32
c1の型:  int32


In [38]:
#int16で宣言する場合
d = np.array([1,2],dtype = np.int16)
print("dの型: ",d.dtype)

dの型:  int16


In [46]:
#型の変換
#astype()を使用する
print(d.astype(np.float16).dtype)

float16
